### ISSUE TITLE
 error: ‘EVP_PKEY_FALCON512’ undeclared 

### ISSUE THREAD

**Issue by Rusheelraj** [Martyrshot/OQS-bind#4]
I have configured it using [sudo LDFLAGS="-L/home/dnssec/.local/lib" CPPFLAGS="-I/home/dnssec/.local/include" ./configure], instead of ./configure (stated in instructions).

Later, I tried to make it using, ```$ sudo make```, but i am getting this below error.

![image](https://github.com/Martyrshot/OQS-bind/assets/30828807/3dfe9442-befa-4b2a-a725-cb2154de138a)

Please help me to resolve the above issue

**Comment by Martyrshot** [comment]
This version of bind uses a (now very out of date) forked version of a forked version of openssl. I'm planning to update this project to use the latest version of Open Quantum Safe's openssl fork, but I haven't had the time do so.

If you want to just play around with PQC and DNS (and don't mind the openssl fork is out of date) you should clone my forked version of openssl ([martyrshot/openssl](https://github.com/Martyrshot/openssl)), build it, then build bind with that version of openssl.

**Comment by Martyrshot** [comment]
Hey there, since it's been awhile I'm going to close this issue.

It's worth mention though that the weird forked version of OQS' openssl isn't needed anymore. Instead it requires oqs-provider and openssl 3.2.0-alpha2. :)
